AllCops:
  DisplayCopNames: true
  CacheRootDirectory: '.git'
  Exclude:
    - coverage/**/*
  TargetRubyVersion: 2.5


### Lint

Lint/NestedMethodDefinition:
  Exclude:
    - api/sinatra/**/*

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

### Metrics

Metrics/AbcSize:
  Max: 18
  Severity: refactor
  Exclude:
    - 'api/sinatra/**/*'
    - 'app/api/routes.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - '**/*.rake'
    - 'api/**/*'
    - 'app/api/routes.rb'
    - 'config/initialize/**/*'
    - 'config/initializers/**/*'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Severity: refactor

Layout/LineLength:
  Max: 119
  Exclude:
    - Guardfile
    - Gemfile
  IgnoreCopDirectives: true

Metrics/MethodLength:
  CountComments: false # count full line comments?
  Max: 10
  Severity: refactor
  Exclude:
    - 'api/sinatra/**/*'
    - 'app/api/routes.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/api/routes.rb'
    - 'spec/requests/**/*'

### Style / Layout

#### Hash
Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Layout/MultilineOperationIndentation:
  Description: Checks indentation of binary operations that span more than one line.
  EnforcedStyle: indented

#### Rest
Style/ArgumentsForwarding:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/DoubleNegation:
  Enabled: false

Style/ExponentialNotation:
  # https://docs.rubocop.org/rubocop/cops_style.html#styleexponentialnotation
  Enabled: true
  EnforcedStyle: engineering

Style/NegatedIfElseCondition:
  Enabled: true

Style/NumericLiterals:
  Description: Add underscores to large numeric literals to improve their readability.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SwapValues:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

### RSpec

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*

RSpec/ExampleLength:
  Enabled: false

RSpec/ExampleWording:
  IgnoredWords:
    - only
  CustomTransform:
    have: has

RSpec/FilePath:
  Exclude:
    - spec/**/*

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
